### ISSUE TITLE
Migrate partners to api v3

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#581]
Known partners of api-v3.balancer.fi:
- aura (vebal voting list)
- paladin (vebal voting list)
- stake dao (vebal voting list)
- lqdr (pool apr)
- reaper (pool apr)
- hidden hand(vebal voting list)

Tasks
- [ ] Investigate API key management (ratelimits, allow lists, on boarding, management, etc)
- [ ] Investigate TG group for announcement of changes/outages etc.
- [ ] Identify partners that use api.balancer.fi
- [ ] Migrate cowswap for the SOR and/or ORDER endpoints
